# Generated by Django 5.0.3 on 2024-03-19 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(db_index=True, max_length=75)),
                ('email', models.EmailField(max_length=50)),
                ('secret_key', models.CharField(max_length=50, unique=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account',
                'ordering': ['-pk'],
            },
        ),
    ]
